### ISSUE TITLE
cannot-find-start-file und Datentyp ist falsch

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.yamaha-community#9]
Hallo,

1. 
https://forum.iobroker.net/topic/26460/yamaha-community-0-cannot-find-start-file
 
2. 
Datentyp ist falsch 

``(1289) You are assigning a number to the state "yamaha.0.volume" which expects a integer. Please fix your code to use a integer or change the state type to number. This warning might become an error .........``

**Comment by metaxa1** [comment]
Was noch nichts an dem scheinbar fehlenden Start-File ändert.
yamaha-community-0-cannot-find-start-file

**Comment by sigi2345** [comment]
> Was noch nichts an dem scheinbar fehlenden Start-File ändert.
> yamaha-community-0-cannot-find-start-file

Zitat von apollon77:
Denke der ist einfach noch nicht vollständig von soef auf Community umgebaut.

**Comment by Apollon77** [comment]
name updated

**Comment by Apollon77** [comment]
Wrong datapoint still open
